### ISSUE TITLE
Not Working in Python 3.6

### ISSUE THREAD

**Issue by fny** [kgritesh/pip-save#3]
Not sure if this is intended, but keep getting this error when running pip-save:

```
Traceback (most recent call last):
  File "/Users/faraz/.pyenv/versions/3.6.2/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'pip-save'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/faraz/.pyenv/versions/3.6.2/envs/sepsis-watch-3.6/bin/pip-save", line 11, in <module>
    load_entry_point('pip-save==0.2.0', 'console_scripts', 'pip-save')()
  File "/Users/faraz/.pyenv/versions/3.6.2/envs/sepsis-watch-3.6/lib/python3.6/site-packages/pip_save/cli.py", line 177, in main
    config_dict = parse_config()
  File "/Users/faraz/.pyenv/versions/3.6.2/envs/sepsis-watch-3.6/lib/python3.6/site-packages/pip_save/cli.py", line 46, in parse_config
    config_dict['requirement'] = config.get('pip-save', 'requirement')
  File "/Users/faraz/.pyenv/versions/3.6.2/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/Users/faraz/.pyenv/versions/3.6.2/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'pip-save'
```

**Comment by netfl0** [comment]
you have to create a .pipconfig file with the following:
```
[pip-save]
use_compatible = false            # example setting
```
